server:
  port: 32000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: sample-server-post
          uri: lb://sample-server
          predicates:
            - Path=/sample/online/{id},/sample/offline/{id}
            - Method=POST
        - id: sample-server-get
          uri: lb://sample-server
          predicates:
            - Path=/sample/{id}
            - Method=GET
        - id: spring-boot-spring-security-jwt-authentication
          uri: lb://spring-boot-spring-security-jwt-authentication
          predicates:
            - Path=/login, /register, /register/admin
            - Method=POST
        - id: delegation-server-post
          uri: lb://delegation-server
          predicates:
            - Path=/complete/delegation/{id},/offer/reply/delegation/{id},/offer/delegation/{id},/delegation/applicationTable,/audit/delegation/test/{id},/audit/delegation/market/{id},/delegation/{id}/files,/delegation/{id}/functionTable
            - Method=POST
        - id: delegation-server-get
          uri: lb://delegation-server
          predicates:
            - Path=/delegations/{id},/delegation/{id},/delegations,/delegation/{id}/files,/delegation/{id}/functionTable
            - Method=GET
        - id: delegation-server-put
          uri: lb://delegation-server
          predicates:
            - Path=/offer/delegation/{id},/delegation/{id}/applicationTable,/delegation/{id}/functionTable
            - Method=PUT
        - id: delegation-server-delete
          uri: lb://delegation-server
          predicates:
            - Path=/delegation/{id}
            - Method=DELETE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:32001/eureka/

