server:
  port: 32000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: sample-server-post
          uri: lb://sample-server
          predicates:
            - Path=/sample/accept/{id},/sample/online/{id},/sample/offline/{id}
            - Method=POST
        - id: sample-server-put
          uri: lb://sample-server
          predicates:
            - Path=/sample/online/{id},/sample/offline/{id}
            - Method=put
        - id: sample-server-get
          uri: lb://sample-server
          predicates:
            - Path=/sample/{id}
            - Method=GET
        - id: spring-boot-spring-security-jwt-authentication
          uri: lb://spring-boot-spring-security-jwt-authentication
          predicates:
            - Path=/login, /register, /register/admin
            - Method=POST
        - id: delegation-server-post
          uri: lb://delegation-server
          predicates:
            - Path=/complete/delegation/{id},/offer/reply/delegation/{id},/offer/delegation/{id},/delegation/applicationTable,/audit/delegation/test/{id},/audit/delegation/market/{id},/delegation/{id}/files,/delegation/{id}/functionTable
            - Method=POST
        - id: delegation-server-get
          uri: lb://delegation-server
          predicates:
            - Path=/delegations/all,/delegations/state/{id},/delegations/usrId/{id},/delegation/{id},/delegations,/delegation/{id}/files,/delegation/{id}/functionTable
            - Method=GET
        - id: delegation-server-put
          uri: lb://delegation-server
          predicates:
            - Path=/offer/delegation/{id},/delegation/{id}/applicationTable,/delegation/{id}/functionTable
            - Method=PUT
        - id: delegation-server-delete
          uri: lb://delegation-server
          predicates:
            - Path=/delegation/{id}
            - Method=DELETE
        - id: contract-server-get
          uri: lb://contract-server
          predicates:
            - Path=/contract/performanceTerm/partyA,/contract/{id}/performanceTerm/partyB,/contract/{id}/contractTable/partyA,/contract/{id}/files/unsignedContractTable,/contract/{id}/files/unsignedNondisclosureAgreementTable,/contract/{id}/files/signedContractTable,/contract/{id}/files/signedNondisclosureAgreementTable,/contract/{id},/contract/delegationId/{id}
            - Method=GET
        - id: contract-server-post
          uri: lb://contract-server
          predicates:
            - Path=/contract/performanceTerm/partyB,/contract/{id}/performanceTerm/partyA,/contract/{id}/contractTable/partyB,/contract/{id}/contractTable/partyA,/contract/{id}/files
            - Method=POST
        - id: contract-server-put
          uri: lb://contract-server
          predicates:
            - Path=/contract/{id}/performanceTerm/partyB
            - Method=PUT

        - id: test-server-testScheme
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-scheme,
            - Method=GET,POST,PUT

        - id: test-server-testSchemeAudit-get
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-scheme/audit-table
            - Method=GET

        - id: test-server-testSchemeAudit-postput
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/audit-scheme
            - Method=POST,PUT

        - id: test-server-testCase
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-doc/test-case
            - Method=GET,POST,PUT

        - id: test-server-testRecord
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-doc/test-record
            - Method=GET,POST,PUT

        - id: test-server-bugList
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-doc/buglist
            - Method=GET,POST,PUT

        - id: test-server-docEvaluation
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-doc/doc-evaluation
            - Method=GET,POST,PUT

        - id: test-server-testReport
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-doc/test-report
            - Method=GET,POST,PUT

        - id: test-server-docEvaluation
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-doc/doc-evaluation
            - Method=GET,POST,PUT

        - id: test-server-reportEvaluation-postput
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-doc/report-evaluation
            - Method=POST,PUT

        - id: test-server-reportEvaluation-get
          uri: lb://test-server
          predicates:
            - Path=/test/{delegationId}/test-doc/test/report-evaluation
            - Method=GET

        - id: test-server-workEvaluation
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-doc/work-evaluation
            - Method=POST,PUT

        - id: test-server-getWorkEvaluation
          uri: lb://test-server
          predicates:
            - Path=/test/{id}/test-doc/test/work-evaluation
            - Method=GET

        - id: test-server-applyEvaluation
          uri: lb://test-server
          predicates:
            - Path=/test/{delegationId}/apply-report-evaluation
            - Method=PUT

        - id: test-server-listProjects
          uri: lb://test-server
          predicates:
            - Path=/test/projects
            - Method=GET

        - id: test-server-listAllProjects
          uri: lb://test-server
          predicates:
            - Path=/test/projects/all
            - Method=GET

        - id: test-server-findProjectByDelegationId
          uri: lb://test-server
          predicates:
            - Path=/test/projects/{delegationId}
            - Method=GET

        - id: test-server-findLatexByDelegationId
          uri: lb://test-server
          predicates:
            - Path=/test/{delegationId}/latexReport
            - Method=GET

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:32001/eureka/

