server:
  port: 8000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: spring-boot-spring-security-jwt-authentication
          uri: lb://spring-boot-spring-security-jwt-authentication
          predicates:
            - Path=/login, /register
            - Method=POST
        - id: delegation-server-post
          uri: lb://delegation-server
          predicates:
            - Path=/delegation/applicationTable,/audit/delegation/{id},/delegation/{id}/files
            - Method=POST
        - id: delegation-server-get
          uri: lb://delegation-server
          predicates:
            - Path=/delegation/{id},/delegations,/delegation/{id}/files
            - Method=GET
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            #allow-credentials: true
#            allowed-origin-patterns: "*"
#            allowed-headers: "*"
#            allowed-methods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - OPTIONS
#            max-age: 3600

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

