server:
  port: 32103
spring:
  application:
    name: test-server
eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:32001/eureka/


