server:
  port: 9998
spring:
  application:
    name: test-server
eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8002/eureka/


