server:
  port: 0
spring:
  application:
    name: gateway-server
eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8002/eureka/

