server:
  port: 9000
spring:
  application:
    name: delegation-server
eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8002/eureka/
#minio
minio:
  endPoint: http://42.192.56.231:9001
  accessKey: admin
  secretKey: password
# bucketName: minioTest
  partSize: 104857600

