@startuml 合同创建
title 合同创建

市场部->合同草稿:起草草稿

alt 创建成功

    质检部->合同草稿:审核合同
    市场部->合同草稿:确认合同
    用户->合同草稿:确认合同
    市场部->合同草稿:打印合同

else 修改合同
    loop 三方尚未确认合同并且合同存在
        市场部->合同草稿:修改合同
        用户->合同草稿:修改合同
    end

else 删除合同，结束委托关系
    alt 市场部删除合同
        市场部->合同草稿:删除合同
    else 用户删除合同
        用户->合同草稿:删除合同
    end

end
@enduml
