@startuml
title 合同生成
alt 市场部未发布测试报告或发布后撤回

alt 质检部未审核通过测试报告
    loop 测试报告尚未完成
        测试部->测试报告 : 填写相关表项
        测试部->测试报告 : 暂存测试报告
    end
        测试部->测试报告 : 上传测试报告
        质检部->测试报告 : 驳回测试报告
else 质检部审核通过质检报告
    loop 测试报告尚未完成
        测试部->测试报告 : 填写相关表项
        测试部->测试报告 : 暂存测试报告
    end
        测试部->测试报告 : 上传测试报告
        质检部->测试报告 : 通过测试报告
end
    市场部->测试报告 : 将测试报告设置为可见
else 因不可抗力，市场部发布测试报告后需要撤回
    市场部->测试报告 : 撤回

end


@enduml