#minio
minio:
  endPoint: http://210.28.133.13:32004
  accessKey: admin
  secretKey: password
  # bucketName: minioTest
  partSize: 104857600
server:
  port: 32102
spring:
  application:
    name: sample-server
eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:32001/eureka/