#minio
minio:
  endPoint: http://42.192.56.231:32004
  accessKey: minioadmin
  secretKey: minioadmin
  # bucketName: minioTest
  partSize: 1048576000000
server:
  port: 32102
spring:
  application:
    name: sample-server
eureka:
  instance:
    hostname: localhost
  # standalone mode
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:32001/eureka/