openapi: "3.0.3"
info:
  version: 0.0.1
  title: Micro
  license:
    name: MIT
servers:
  - url: http://localhost:8000
paths:
  /delegation:
    post:
      summary: creat delegation
      operationId: creatDelegation
      tags:
        - delegation
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/creatDelegationRequest"
        required: true
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  delegationId:
                    type: string
        '400':
          description: error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorInfo:
                    type: string

components:
  schemas:
    delegationApplicationTable:
      type: object
      properties:
        name:
          type: string
    delegationFunctionTable:
      type: object
      properties:
        name:
          type: string
    delegationFileList:
      type: object
      properties:
        fileName:
          type: array
          items:
            type: string
    creatDelegationRequest:
      type: object
      properties:
        applicationTable:
          $ref: "#/components/schemas/delegationApplicationTable"
        functionTable:
          $ref: "#/components/schemas/delegationFunctionTable"
        fileList:
          $ref: "#/components/schemas/delegationFileList"