openapi: "3.0.3"
info:
  version: 0.0.1
  title: Micro
  license:
    name: MIT
servers:
  - url: http://localhost:32000
paths:
  /sampleServer/private/startApplication:
    post:
      summary: start a sample application process in sample-server
      operationId: startSampleApplication
      tags:
        - sample
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/startSampleApplicationRequest"
      responses:
        '200':
          description: process started

  /sample/online/{id}:
    parameters:
      - name: usrName
        in: header
        required: true
        schema:
          type: string
      - name: usrId
        in: header
        required: true
        schema:
          type: string
      - name: usrRole
        in: header
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: createSampleFile
      tags:
        - sample
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                # The property name 'file' will be used for all files.
                sample:
                  type: string
                  format: binary
      responses:
        '201':
          description: created
        '404':
          description: id not found

  /sample/offline/{id}:
    parameters:
      - name: usrName
        in: header
        required: true
        schema:
          type: string
      - name: usrId
        in: header
        required: true
        schema:
          type: string
      - name: usrRole
        in: header
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: createSampleMessage
      tags:
        - sample
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/sampleMessageApplicationRequest"
      responses:
        '201':
          description: created
        '404':
          description: id not found

  /sample/{id}:
    parameters:
      - name: usrName
        in: header
        required: true
        schema:
          type: string
      - name: usrId
        in: header
        required: true
        schema:
          type: string
      - name: usrRole
        in: header
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
    get:
      operationId: getSample
      tags:
        - sample
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getSampleResponse"
        '404':
          description: not found
components:
  schemas:
    startSampleApplicationRequest:
      type: object
      properties:
        id:
          type: string
        applicationMethod:
          type: string
    sampleMessageApplicationRequest:
      type: object
      properties:
        number:
          type: string
    getSampleResponse:
      type: object
      properties:
        applicationMethod:
          type: string
        number:
          type: string
        uri:
          type: string
