bezkoder:
    app:
        jwtExpirationMs: 864000000
        jwtSecret: bezKoderSecretKey
eureka:
    client:
        service-url:
            defaultZone: http://localhost:32001/eureka/
server:
    port: 32100
spring:
    application:
        name: spring-boot-spring-security-jwt-authentication
    datasource:
        password: goodman
        #url: jdbc:mysql://210.28.133.13:21252/testUsrDb?useSSL=false&allowPublicKeyRetrieval=True&autoReconnect=true
        url: jdbc:mysql://localhost:32002/testUsrDb?useSSL=false&allowPublicKeyRetrieval=True&autoReconnect=true
        username: saul
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
