@startuml 检查软件样品可测状态
title 检查软件样品可测状态
skinparam dpi 900

actor 客户
entity 测试项目
actor 测试人员

客户 -> 测试项目: 上传软件样品
测试项目 -> 测试人员 : 发送软件样品上传通知
测试人员 <- 测试项目 : 下载软件样品
客户 -> 测试项目: 查看软件样品审核状态
loop 软件样品未达可测状态
    测试人员 -> 测试项目 : 拒绝接收软件样品，编写反馈意见
    测试项目 -> 客户 : 收到拒绝接收软件样品的通知
    客户 -> 测试项目: 查看软件样品反馈意见
    客户 -> 测试项目 : 上传软件样品
    测试项目 -> 测试人员 : 发送软件样品上传通知
    测试项目 -> 测试人员 : 下载软件样品
    客户 -> 测试项目: 查看软件样品审核状态
end
测试人员 -> 测试项目 : 同意接收软件样品
测试项目 -> 客户 : 收到同意接收软件样品的通知

@enduml