@startuml 工作人员登录
title 工作人员登录
skinparam dpi 900

actor 工作人员
entity 网页
database 数据库

工作人员 -> 网页 : 点击"我是工作人员"按钮
工作人员 -> 网页 : 填写用户名
工作人员 -> 网页 : 填写密码
工作人员 -> 网页 : 点击"登录"按钮
网页 -> 数据库 : 提交工作人员登录信息
loop 工作人员登录信息填写错误
    数据库 -> 网页 : 返回工作人员名/密码无法匹配
    网页 -> 工作人员 : 反馈登录失败，工作人员不存在/密码错误
    工作人员 -> 网页 : 填写工作人员名
    工作人员 -> 网页 : 填写密码
    工作人员 -> 网页 : 点击"登录"按钮
    网页 -> 数据库 : 提交工作人员登录信息
end
数据库 -> 网页 : 返回工作人员信息成功匹配
网页 -> 工作人员 : 反馈登录成功

@enduml