@startuml 实施软件测试
title 实施软件测试
skinparam dpi 900

actor 测试人员
entity 测试项目
actor 质量部人员

测试项目 -> 测试人员 : 下载软件样品
测试项目 -> 测试人员 : 下载项目支持文档
测试人员 -> 测试项目 : 填写测试文档
测试项目 <- 测试项目 : 生成测试报告
测试项目 -> 质量部人员 : 收到上传测试报告的通知
测试项目 -> 质量部人员 : 下载测试报告
测试人员 -> 测试项目 : 查看测试报告审核状态
质量部人员 -> 测试项目 : 审核不通过，填写测试报告检查表
测试项目 -> 测试人员 : 收到测试报告审核不通过的通知
测试项目 -> 测试人员 : 下载测试报告检查表
测试人员 -> 测试项目 : 重新填写测试文档
测试项目 <- 测试项目 : 生成测试报告
测试项目 -> 质量部人员 : 收到上传测试报告的通知
测试项目 -> 质量部人员 : 下载测试报告
测试人员 -> 测试项目 : 查看测试报告审核状态
质量部人员 -> 测试项目 : 审核通过，填写测试报告检查表
测试项目 -> 测试人员 : 收到测试报告审核通过的通知




@enduml