@startuml 实施软件测试
title 实施软件测试
skinparam dpi 500

actor 测试人员
entity 测试项目
actor 质量部人员
actor 市场部人员

测试项目 -> 测试人员 : 下载软件样品
测试项目 -> 测试人员 : 下载项目支持文档
测试人员 -> 测试项目 : 填写测试文档
测试项目 <- 测试项目 : 生成测试报告
测试人员 -> 测试项目 : 下载并审核测试报告
loop 测试报告审核不通过
    测试人员 -> 测试项目 : 填写测试文档
    测试项目 <- 测试项目 : 生成测试报告
    测试人员 -> 测试项目 : 下载并审核测试报告
end
测试人员 -> 测试项目 : 上传测试报告
测试项目 -> 质量部人员 : 收到上传测试报告的通知
测试项目 -> 质量部人员 : 下载测试报告
测试人员 -> 测试项目 : 查看测试报告形式检查状态
loop 测试报告形式检查不通过
    质量部人员 -> 测试项目 : 形式检查不通过，填写测试报告检查表
    测试项目 -> 测试人员 : 收到测试报告形式检查不通过的通知
    测试项目 -> 测试人员 : 下载测试报告检查表
    测试人员 -> 测试项目 : 重新填写测试文档
    测试项目 <- 测试项目 : 生成测试报告
    测试人员 -> 测试项目 : 下载并审核测试报告
    loop 测试报告审核不通过
        测试人员 -> 测试项目 : 重新填写测试文档
        测试项目 <- 测试项目 : 生成测试报告
        测试人员 -> 测试项目 : 下载并审核测试报告
    end
    测试人员 -> 测试项目 : 上传测试报告
    测试项目 -> 质量部人员 : 收到上传测试报告的通知
    测试项目 -> 质量部人员 : 下载测试报告
    测试人员 -> 测试项目 : 查看测试报告形式检查状态
end
质量部人员 -> 测试项目 : 形式检查通过，填写测试报告检查表
测试项目 -> 测试人员 : 收到测试报告形式检查通过的通知
市场部人员 -> 测试项目 : 批准签发测试报告
测试项目 -> 测试人员 : 收到测试报告已批准签发的通知




@enduml