@startuml 用户注册
title 用户注册
skinparam dpi 800

actor 用户
entity 网页
database 数据库

用户 -> 网页 : 点击"我是用户"按钮
用户 -> 网页 : 点击"注册"按钮
用户 -> 网页 : 填写用户名
用户 -> 网页 : 填写密码
用户 -> 网页 : 填写确认密码
用户 -> 网页 : 填写邮箱
用户 -> 网页 : 填写电话
用户 -> 网页 : 点击"确认注册"按钮
网页 -> 数据库 : 提交用户注册信息
loop 用户重复注册
    数据库 -> 网页 : 返回重复注册
    网页 -> 用户 : 反馈注册失败，重复注册
    用户 -> 网页 : 填写用户名
    用户 -> 网页 : 填写密码
    用户 -> 网页 : 填写确认密码
    用户 -> 网页 : 填写邮箱
    用户 -> 网页 : 填写电话
    用户 -> 网页 : 点击"确认注册"按钮
    网页 -> 数据库 : 提交用户注册信息
end
数据库 <- 数据库 : 添加用户信息
数据库 -> 网页 : 返回未重复注册
网页 -> 用户 : 反馈注册成功，请登录

@enduml