@startuml 编写测试方案
title 编写测试方案
skinparam dpi 1080

actor 测试人员
entity 测试项目
actor 质量部人员

测试人员 -> 测试项目 : 填写测试方案
测试项目 -> 质量部人员 : 收到测试方案上传的通知
测试项目 -> 质量部人员 : 查看并审核测试方案
测试人员 -> 测试项目 : 查看测试方案审核状态
质量部人员 -> 测试项目 : 审核不通过，反馈测试方案修改意见
测试项目 -> 测试人员 : 收到测试方案审核不通过的通知
测试人员 -> 测试项目 : 查看测试方案修改意见
测试人员 -> 测试项目 : 重新填写测试方案
测试项目 -> 质量部人员 : 收到测试方案上传的通知
测试项目 -> 质量部人员 : 查看并审核测试方案
测试人员 -> 测试项目 : 查看测试方案审核状态
质量部人员 -> 测试项目 : 审核通过
测试项目 -> 测试人员 : 收到测试方案审核通过的通知

@enduml