@startuml 编写测试方案
title 编写测试方案
skinparam dpi 800

actor 测试人员
entity 测试项目
actor 质量部人员

测试人员 -> 测试项目 : 填写测试方案
测试人员 -> 测试项目 : 填写测试方案评审表
loop 测试方案评审未通过
    测试人员 -> 测试项目 : 填写测试方案
    测试人员 -> 测试项目 : 填写测试方案评审表
end
    测试项目 -> 质量部人员 : 收到测试方案上传的通知
    测试项目 -> 质量部人员 : 下载测试方案
    测试人员 -> 测试项目 : 查看测试方案批准状态
loop 测试方案未被批准
    质量部人员 -> 测试项目 : 不批准测试方案，反馈修改意见
    测试项目 -> 测试人员 : 收到测试方案未批准的通知
    测试人员 -> 测试项目 : 查看测试方案修改意见
    测试人员 -> 测试项目 : 填写测试方案
    测试人员 -> 测试项目 : 填写测试方案评审表
    loop 测试方案评审未通过
        测试人员 -> 测试项目 : 填写测试方案
        测试人员 -> 测试项目 : 填写测试方案评审表
    end
    测试项目 -> 质量部人员 : 收到测试方案上传的通知
    测试项目 -> 质量部人员 : 下载测试方案
    测试人员 -> 测试项目 : 查看测试方案批准状态
end

质量部人员 -> 测试项目 : 批准测试方案
测试项目 -> 测试人员 : 收到测试方案已批准的通知

@enduml